stan-core:
  stanPath: .stan
  excludes:
    - '**/.tsbuild/**'
    - '**/*.tsbuildinfo'
    - assets
    - CHANGELOG.md
    - docs
    - package-lock.json
stan-cli:
  scripts:
    typecheck: npm run typecheck
    lint: npm run lint
    test: npm run test
    diagrams: npm run diagrams
    docs: npm run stan:docs
    build: npm run stan:build
    knip: npm run knip
  cliDefaults:
    run:
      facets: false
      plan: false
      sequential: true
  patchOpenCommand: code -g {file}

